### ISSUE TITLE
Reload command

### ISSUE THREAD

**Issue by zaanposni** [bundestagsbot/bundestagsBot#20]
**Roadmap**
Keep in mind that every action should be according to the definitions at <a href="https://github.com/zaanposni/bundestagsBot/projects/1">roadmap</a>.<hr/>

Add reload command (team cmd):
- [x] Calls [config.py](https://github.com/bundestagsbot/bundestagsBot/blob/dev/bt_utils/config.py) `cfg.reload()`
- [x] Returns embed
     - [x] Shows how many keys got loaded
     - [x] Returns if an error occurred

^ Edit [config.py](https://github.com/bundestagsbot/bundestagsBot/blob/dev/bt_utils/config.py) to achieve this.
